// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzaHGx5lRLS36lUAYGwRYR1kO3oKFvHYA',
    appId: '1:492784035117:web:89f5e757964d12606e1fa4',
    messagingSenderId: '492784035117',
    projectId: 'chat-example-3d1d6',
    authDomain: 'chat-example-3d1d6.firebaseapp.com',
    databaseURL: 'https://chat-example-3d1d6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-example-3d1d6.appspot.com',
    measurementId: 'G-3ZWHGQT5ZN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73k7OHhkd1uS-IMb3yO2lE4VwB5IqUWQ',
    appId: '1:492784035117:ios:4d1c31dc54d2a5496e1fa4',
    messagingSenderId: '492784035117',
    projectId: 'chat-example-3d1d6',
    databaseURL: 'https://chat-example-3d1d6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-example-3d1d6.appspot.com',
    iosBundleId: 'com.example.chatTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73k7OHhkd1uS-IMb3yO2lE4VwB5IqUWQ',
    appId: '1:492784035117:ios:5f6933268263c79f6e1fa4',
    messagingSenderId: '492784035117',
    projectId: 'chat-example-3d1d6',
    databaseURL: 'https://chat-example-3d1d6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-example-3d1d6.appspot.com',
    iosBundleId: 'com.example.chatTest.RunnerTests',
  );
}
